### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by Vad1mo** [c4po/harbor_exporter#40]
The application starts up correctly, but when I do `curl http://localhost:9107/metrics`

The application crashes. It might be because we are using OIDC but I am not sure.

Error Message + Stack Trace:
```sh
level=info ts=2020-09-07T21:55:29.794Z caller=harbor_exporter.go:333 CacheEnabled=false
level=info ts=2020-09-07T21:55:29.794Z caller=harbor_exporter.go:334 CacheDuration=20s
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:336 msg="Starting harbor_exporter" version="(version=v0.5.3, branch=master, revision=738e855f8164aefa8e65b8fa996054c984fc552c)"
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:337 build_context="(go=go1.13.15, user=root, date=2020-09-07-01:52:25-UTC)"
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:348 metrics_group=scans collect=true
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:348 metrics_group=statistics collect=true
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:348 metrics_group=quotas collect=true
level=info ts=2020-09-07T21:55:29.795Z caller=harbor_exporter.go:348 metrics_group=repositories collect=true
level=info ts=2020-09-07T21:55:29.797Z caller=harbor_exporter.go:348 metrics_group=replication collect=true
level=info ts=2020-09-07T21:55:30.041Z caller=harbor_exporter.go:211 msg="check v1 with /api/systeminfo" code=404
level=info ts=2020-09-07T21:55:30.244Z caller=harbor_exporter.go:222 msg="check v2 with /api/v2.0/systeminfo" code=200
level=info ts=2020-09-07T21:55:30.244Z caller=harbor_exporter.go:386 msg="Listening on address" address=:9107
panic: send on closed channel

goroutine 44 [running]:
main.(*HarborExporter).Collect.func1(0xc0001aed80, 0xc0001d4d20, 0xc0001a8000)
	/src/harbor_exporter.go:266 +0x90
created by main.(*HarborExporter).Collect
	/src/harbor_exporter.go:264 +0x232
```

**Comment by c4po** [comment]
@Nick-Triller  can you check if this is related to your commits?

**Comment by c4po** [comment]
@Vad1mo  Sorry I didn't test it our before release the new version. This may related to a new feature for caching. I just rolled back to v0.5.2. can you try it again?

**Comment by Nick-Triller** [comment]
Hi, sorry about that, this bug slipped past me because it only happens when the timing is unlucky. https://github.com/c4po/harbor_exporter/pull/41 fixes this issue.

**Comment by Vad1mo** [comment]
thank you, now it works
